openapi: 3.0.1
info:
  title:
    Products API
  version: 1.0.0

servers:
  - url: https://kkyi46yfn1.execute-api.us-east-1.amazonaws.com/Lambdaless

security:
  - ApiKeyAuth: []

paths:
  /products:
    get:
      responses:
        200:
          description: The request succeded and results are in the response message.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/responses/Product"

      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS
        uri: { "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:dynamodb:action/Scan" }
        credentials: { "Fn::GetAtt": [ ProductsAPIRole, Arn ] }
        requestTemplates:
          application/json:
            Fn::Sub:
              - |-
                {
                  "TableName": "${tableName}"
                }
              - { tableName: { Ref: ProductsTable } }
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: '#set($inputRoot = $input.path("$"))
                          [
                            #foreach($elem in $inputRoot.Items) {
                              "id": "$elem.pk.S",
                              "name": "$elem.productname.S"
                            }#if($foreach.hasNext),#end
                            #end
                          ]'

    post:
      responses:
        201:
          $ref: "#/components/responses/Created"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS
        uri: { "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:dynamodb:action/PutItem" }
        credentials: { "Fn::GetAtt": [ ProductsAPIRole, Arn ] }
        requestTemplates:
          application/json:
            Fn::Sub:
              - |-
                {
                  "TableName": "${tableName}",
                  "Item": {
                    "pk": {
                      "S": "$context.requestId"
                    },
                    "productname": {
                      "S": "$input.path("$.name")"
                    }
                  }
                }
              - { tableName: { Ref: ProductsTable } }
        responses:
          default:
            statusCode: 201
            responseTemplates:
              application/json: '#set($inputRoot = $input.path("$"))
                {
                    "id": "$context.requestId"
                }'
  /products/{productId}:
    get:
      parameters:
        - name: "productId"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/Product"
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS
        uri: { "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:dynamodb:action/GetItem" }
        credentials: { "Fn::GetAtt": [ ProductsAPIRole, Arn ] }
        requestTemplates:
          application/json:
            Fn::Sub:
              - |-
                {
                  "TableName": "${tableName}",
                  "Key": {
                          "pk": {
                            "S": "$input.params("productId")"
                          }
                        }
                }
              - { tableName: { Ref: ProductsTable } }
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: '#set($inputRoot = $input.path("$"))
                {
                    "id": "$inputRoot.Item.pk.S",
                    "name": "$inputRoot.Item.productname.S"
                }'

    put:
      parameters:
        - name: "productId"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        204:
          description: The product was updated
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS
        uri: { "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:dynamodb:action/UpdateItem" }
        credentials: { "Fn::GetAtt": [ ProductsAPIRole, Arn ] }
        requestTemplates:
          application/json:
            Fn::Sub:
              - |-
                {
                  "TableName": "${tableName}",
                  "Key": {
                          "pk": {
                            "S": "$input.params("productId")"
                          }
                        },
                  "UpdateExpression": "SET productname = :name",
                  "ExpressionAttributeValues": {
                    ":name":  {
                                "S": "$input.path("$.name")"
                              }
                  }
                }
              - { tableName: { Ref: ProductsTable } }
        responses:
          default:
            statusCode: 204

    delete:
      parameters:
      - name: "productId"
        in: "path"
        required: true
        schema:
            type: string
      responses:
        204:
          description: The product was deleted
      x-amazon-apigateway-integration:
        credentials: { "Fn::GetAtt": [ ProductsAPIRole, Arn ] }
        uri: { "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:dynamodb:action/DeleteItem" }
        requestTemplates:
          application/json:
            Fn::Sub:
              - |-
                {
                  "TableName": "${tableName}",
                    "Key": {
                      "pk": {
                        "S": "$input.params("productId")"
                      }
                    },
                  "ReturnValues": "ALL_OLD"
                }
              - { tableName: { Ref: ProductsTable } }
        responses:
          default:
            statusCode: 204
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    Product:
      type: object
      description: Product
      properties:
        id:
          type: string
        name:
          type: string
  responses:
    Created: #201
      description: The request succeeded and created a new resource.
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
            required:
              - id
    Empty:
      description: Empty Schema
      content:
        application/json:
          schema:
            type: object

    Product:
      description: Product
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              id:
                type: string
              name:
                type: string